### PR TITLE
GCNV-34 Initial App

### PR DESCRIPTION
**Pull request by Addy81**
App that takes in a gCNV vcf and adds length it. Given the same vcf the app also can create a seg file for IGV visualisation.

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_additional_cnv_tasks/1)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_additional_cnv_tasks/1)* status: 2 of 13 files reviewed, 8 unresolved discussions (waiting on @Addy81 and @jethror1)

___
*[`dxapp.json` line 4 at r2](https://reviewable.io/reviews/eastgenomics/eggd_additional_cnv_tasks/1#-N9gFHM8Bb9mgbFiyTEx:-N9gFHM9ARhC41yC8uyq:b-l9n9kf) ([raw file](https://github.com/eastgenomics/eggd_additional_cnv_tasks/blob/ba97b9dd7bffada256a10408c46398694a52037d/dxapp.json#L4)):*
> ```JSON
>   "name": "eggd_additional_cnv_tasks",
>   "title": "eggd_additional_cnv_tasks",
>   "summary": "Adds length to CNV  VCF and creates seg file for visualisation",
> ```

extra space



_Code quote:_
```JSON
CNV  VCF
```
___
*[`dxapp.json` line 28 at r2](https://reviewable.io/reviews/eastgenomics/eggd_additional_cnv_tasks/1#-N9gFhtbDmKu5SFbP18e:-N9gFhtbDmKu5SFbP18f:b-6fw2rg) ([raw file](https://github.com/eastgenomics/eggd_additional_cnv_tasks/blob/ba97b9dd7bffada256a10408c46398694a52037d/dxapp.json#L28)):*
> ```JSON
>       "optional": true,
>       "default": false,
>       "help": "Boolean option if only vcf needed"
> ```

should this be if only length needed?



_Code quote:_
```JSON
Boolean option if only vcf needed
```
___
*[`dxapp.json` line 59 at r2](https://reviewable.io/reviews/eastgenomics/eggd_additional_cnv_tasks/1#-N9gFrei83zhnS52X78f:-N9gFrei83zhnS52X78g:bgv87rj) ([raw file](https://github.com/eastgenomics/eggd_additional_cnv_tasks/blob/ba97b9dd7bffada256a10408c46398694a52037d/dxapp.json#L59)):*
> ```JSON
>       "help": ""
>     }
>   ],
> ```

missing authorised devs and users section
___
*[`resources/home/dnanexus/add_length.py` line 4 at r2](https://reviewable.io/reviews/eastgenomics/eggd_additional_cnv_tasks/1#-N9gGLfGB2T8g5fxYkvi:-N9gGLfGB2T8g5fxYkvj:b37mi20) ([raw file](https://github.com/eastgenomics/eggd_additional_cnv_tasks/blob/ba97b9dd7bffada256a10408c46398694a52037d/resources/home/dnanexus/add_length.py#L4)):*
> ```Python
> Reads in vcf and calculates CNVLEN field
> 
> Positional args:
> ```

technically not positional since its a named argument with `--vcf`



_Code quote:_
```Python
Positional
```
___
*[`resources/home/dnanexus/make_seg.py` line 2 at r2](https://reviewable.io/reviews/eastgenomics/eggd_additional_cnv_tasks/1#-N9gGmvz7_LSnW74VB0m:-N9gGmw-4dA9kUPOv0Th:bgnrqx3) ([raw file](https://github.com/eastgenomics/eggd_additional_cnv_tasks/blob/ba97b9dd7bffada256a10408c46398694a52037d/resources/home/dnanexus/make_seg.py#L2)):*
> ```Python
> import pandas as pd
> import argparse
> ```

top pls
___
*[`resources/home/dnanexus/make_seg.py` line 50 at r2](https://reviewable.io/reviews/eastgenomics/eggd_additional_cnv_tasks/1#-N9gI7Z96Givea6YKDf6:-N9gI7Z96Givea6YKDf7:b-9i9elc) ([raw file](https://github.com/eastgenomics/eggd_additional_cnv_tasks/blob/ba97b9dd7bffada256a10408c46398694a52037d/resources/home/dnanexus/make_seg.py#L50)):*
this is a more reliable way to strip the path and any number of suffixes:
```
>>> from pathlib import Path
>>> file='some/path/to/file_with_suffixes.vcf.gz'
>>> Path(file).name.replace(''.join(Path(file).suffixes), '')
'file_with_suffixes'
```

then you can combine with below as:
```
output_seg = f'{Path(patient).name.replace(''.join(Path(patient).suffixes), '.seg')}'
```
___
*[`src/eggd_additional_cnv_tasks.sh` line 46 at r2](https://reviewable.io/reviews/eastgenomics/eggd_additional_cnv_tasks/1#-N9gJ6_b9yYJk5luA89J:-N9gJ6_b9yYJk5luA89K:b-6fac61) ([raw file](https://github.com/eastgenomics/eggd_additional_cnv_tasks/blob/ba97b9dd7bffada256a10408c46398694a52037d/src/eggd_additional_cnv_tasks.sh#L46)):*
> ```Shell
>         mv "${outname}_length.vcf.gz" /home/dnanexus/out/output_vcf/
> 
>     elif [ "$seg_only" == true ];then
> ```

missing space



_Code quote:_
```Shell
;then
```
___
*[`src/eggd_additional_cnv_tasks.sh` line 51 at r2](https://reviewable.io/reviews/eastgenomics/eggd_additional_cnv_tasks/1#-N9gJ97F2BAJd0ANSZhC:-N9gJ97F2BAJd0ANSZhD:bklb3bb) ([raw file](https://github.com/eastgenomics/eggd_additional_cnv_tasks/blob/ba97b9dd7bffada256a10408c46398694a52037d/src/eggd_additional_cnv_tasks.sh#L51)):*
> ```Shell
> 
>     else
> ```

do you need all the blank lines in the if/elif/else ?

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_additional_cnv_tasks/1)* status: 2 of 13 files reviewed, 11 unresolved discussions (waiting on @Addy81, @Aisha-D, and @jethror1)

___
*[`resources/home/dnanexus/add_length.py` line 59 at r2](https://reviewable.io/reviews/eastgenomics/eggd_additional_cnv_tasks/1#-N9gOjlm-BdfAp51MTZh:-N9gOjlm-BdfAp51MTZi:br1zybd) ([raw file](https://github.com/eastgenomics/eggd_additional_cnv_tasks/blob/ba97b9dd7bffada256a10408c46398694a52037d/resources/home/dnanexus/add_length.py#L59)):*
> ```Python
> if __name__ == "__main__":
>     parser = argparse.ArgumentParser()
>     parser.add_argument('-v', '--vcf')
> ```

some description/help detailing the input 
___
*[`src/eggd_additional_cnv_tasks.sh` line 21 at r2](https://reviewable.io/reviews/eastgenomics/eggd_additional_cnv_tasks/1#-N9gMpvY3qkV4KkP0a2B:-N9gMpvY3qkV4KkP0a2C:b-nw5oaj) ([raw file](https://github.com/eastgenomics/eggd_additional_cnv_tasks/blob/ba97b9dd7bffada256a10408c46398694a52037d/src/eggd_additional_cnv_tasks.sh#L21)):*
> ```Shell
>     export PATH=$PATH:/home/dnanexus/.local/bin  # pip installs some packages here, add to path
> 
>     sudo -H python3 -m pip install --no-index --no-deps packages/*
> ```

do we need sudo when installing locally?
___
*[`src/eggd_additional_cnv_tasks.sh` line 28 at r2](https://reviewable.io/reviews/eastgenomics/eggd_additional_cnv_tasks/1#-N9gMmlr5_edpJzlafl9:-N9gMmlr5_edpJzlaflA:b-5hv2g0) ([raw file](https://github.com/eastgenomics/eggd_additional_cnv_tasks/blob/ba97b9dd7bffada256a10408c46398694a52037d/src/eggd_additional_cnv_tasks.sh#L28)):*
> ```Shell
>     python3 /home/dnanexus/add_length.py --vcf $vcf_name
> 
>     mark-section "Adding length to CNV"
> ```

Making segments here

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_additional_cnv_tasks/1)* status: 2 of 13 files reviewed, 12 unresolved discussions (waiting on @Addy81, @Aisha-D, and @jethror1)

___
*[`src/eggd_additional_cnv_tasks.sh` line 38 at r2](https://reviewable.io/reviews/eastgenomics/eggd_additional_cnv_tasks/1#-N9gP9J-8c4Y06RqzBh6:-N9gP9J09lPXOIeVDRaZ:b-t5aubv) ([raw file](https://github.com/eastgenomics/eggd_additional_cnv_tasks/blob/ba97b9dd7bffada256a10408c46398694a52037d/src/eggd_additional_cnv_tasks.sh#L38)):*
> ```Shell
>     outname=$(sed 's/.vcf\|.gz//g' <<< "$vcf_name")
> 
>     if [ "$length_only" == true ] && [ "$seg_only" == true ]; then
> ```

could move this to the top so it errors out immediately rather than installing and running the scripts

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_additional_cnv_tasks/1)* status: 2 of 13 files reviewed, 12 unresolved discussions (waiting on @Addy81, @Aisha-D, and @jethror1)

___
*[`src/eggd_additional_cnv_tasks.sh` line 38 at r2](https://reviewable.io/reviews/eastgenomics/eggd_additional_cnv_tasks/1#-N9gP9J-8c4Y06RqzBh6:-N9gPiin-Rw7BV-RoZbk:b-y7sc45) ([raw file](https://github.com/eastgenomics/eggd_additional_cnv_tasks/blob/ba97b9dd7bffada256a10408c46398694a52037d/src/eggd_additional_cnv_tasks.sh#L38)):*
<details><summary><i>Previously, Aisha-D (Aisha Dahir) wrote…</i></summary><blockquote>

could move this to the top so it errors out immediately rather than installing and running the scripts
</blockquote></details>

also why exit if both are true? default are false

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 10 of 13 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_additional_cnv_tasks/1)* status: 12 of 13 files reviewed, 13 unresolved discussions (waiting on @Addy81, @Aisha-D, @jethror1, and @mattgarner)

___
*[`dxapp.json` line 23 at r2](https://reviewable.io/reviews/eastgenomics/eggd_additional_cnv_tasks/1#-N9kV0Nf3uT9P8ec0mQv:-N9kV0NgCx5JGv0PlM1S:b-bzqvky) ([raw file](https://github.com/eastgenomics/eggd_additional_cnv_tasks/blob/ba97b9dd7bffada256a10408c46398694a52037d/dxapp.json#L23)):*
> ```JSON
>     },
>     {
>       "name": "length_only",
> ```

I don't think these should be x_only

It could work when there are only 2 things the app does, but if we add a third and only want 2 of the three it doesn't work

Can they just be bools which switch that thing on and off? This would let you ask for A and C from a possible set of outputs A/B/C



_Code quote:_
```JSON
length_only
```

**Review by Addy81 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_additional_cnv_tasks/1)* status: 9 of 13 files reviewed, 13 unresolved discussions (waiting on @Addy81, @Aisha-D, @jethror1, and @mattgarner)

___
*[`dxapp.json` line 4 at r2](https://reviewable.io/reviews/eastgenomics/eggd_additional_cnv_tasks/1#-N9gFHM8Bb9mgbFiyTEx:-N9gRnX8BcA0w1MW0nV8:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_additional_cnv_tasks/blob/ba97b9dd7bffada256a10408c46398694a52037d/dxapp.json#L4)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

extra space
</blockquote></details>

Done.
___
*[`dxapp.json` line 28 at r2](https://reviewable.io/reviews/eastgenomics/eggd_additional_cnv_tasks/1#-N9gFhtbDmKu5SFbP18e:-N9gS5nHAR3NojVbmcVk:bmkwdes) ([raw file](https://github.com/eastgenomics/eggd_additional_cnv_tasks/blob/ba97b9dd7bffada256a10408c46398694a52037d/dxapp.json#L28)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

should this be if only length needed?
</blockquote></details>

Done. - changed help slightly to make clearer
___
*[`dxapp.json` line 59 at r2](https://reviewable.io/reviews/eastgenomics/eggd_additional_cnv_tasks/1#-N9gFrei83zhnS52X78f:-N9gSkdVEVlDpHSiKJB4:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_additional_cnv_tasks/blob/ba97b9dd7bffada256a10408c46398694a52037d/dxapp.json#L59)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

missing authorised devs and users section
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/add_length.py` line 4 at r2](https://reviewable.io/reviews/eastgenomics/eggd_additional_cnv_tasks/1#-N9gGLfGB2T8g5fxYkvi:-N9gTLo53D5crCvMI8i6:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_additional_cnv_tasks/blob/ba97b9dd7bffada256a10408c46398694a52037d/resources/home/dnanexus/add_length.py#L4)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

technically not positional since its a named argument with `--vcf`
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/add_length.py` line 59 at r2](https://reviewable.io/reviews/eastgenomics/eggd_additional_cnv_tasks/1#-N9gOjlm-BdfAp51MTZh:-N9gU7rJ45FF0_8BcsMW:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_additional_cnv_tasks/blob/ba97b9dd7bffada256a10408c46398694a52037d/resources/home/dnanexus/add_length.py#L59)):*
<details><summary><i>Previously, Aisha-D (Aisha Dahir) wrote…</i></summary><blockquote>

some description/help detailing the input 
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/make_seg.py` line 2 at r2](https://reviewable.io/reviews/eastgenomics/eggd_additional_cnv_tasks/1#-N9gGmvz7_LSnW74VB0m:-N9gUEVc-ZfbY3IUd7sz:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_additional_cnv_tasks/blob/ba97b9dd7bffada256a10408c46398694a52037d/resources/home/dnanexus/make_seg.py#L2)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

top pls
</blockquote></details>

Done.
___
*[`src/eggd_additional_cnv_tasks.sh` line 21 at r2](https://reviewable.io/reviews/eastgenomics/eggd_additional_cnv_tasks/1#-N9gMpvY3qkV4KkP0a2B:-N9pgGUWAoijFegQi-tD:b137y5e) ([raw file](https://github.com/eastgenomics/eggd_additional_cnv_tasks/blob/ba97b9dd7bffada256a10408c46398694a52037d/src/eggd_additional_cnv_tasks.sh#L21)):*
<details><summary><i>Previously, Aisha-D (Aisha Dahir) wrote…</i></summary><blockquote>

do we need sudo when installing locally?
</blockquote></details>

Not sure but better be safe than sorry.
___
*[`src/eggd_additional_cnv_tasks.sh` line 28 at r2](https://reviewable.io/reviews/eastgenomics/eggd_additional_cnv_tasks/1#-N9gMmlr5_edpJzlafl9:-N9pgTFV88egOj7KwEWQ:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_additional_cnv_tasks/blob/ba97b9dd7bffada256a10408c46398694a52037d/src/eggd_additional_cnv_tasks.sh#L28)):*
<details><summary><i>Previously, Aisha-D (Aisha Dahir) wrote…</i></summary><blockquote>

Making segments here
</blockquote></details>

Done.
___
*[`src/eggd_additional_cnv_tasks.sh` line 38 at r2](https://reviewable.io/reviews/eastgenomics/eggd_additional_cnv_tasks/1#-N9gP9J-8c4Y06RqzBh6:-N9pgXpX6H-Pla7XWhqa:bzeadq0) ([raw file](https://github.com/eastgenomics/eggd_additional_cnv_tasks/blob/ba97b9dd7bffada256a10408c46398694a52037d/src/eggd_additional_cnv_tasks.sh#L38)):*
<details><summary><i>Previously, Aisha-D (Aisha Dahir) wrote…</i></summary><blockquote>

also why exit if both are true? default are false
</blockquote></details>

I might switch the logic round to make it clearer.
___
*[`src/eggd_additional_cnv_tasks.sh` line 46 at r2](https://reviewable.io/reviews/eastgenomics/eggd_additional_cnv_tasks/1#-N9gJ6_b9yYJk5luA89J:-N9pgkJ87eX77p5JoSrA:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_additional_cnv_tasks/blob/ba97b9dd7bffada256a10408c46398694a52037d/src/eggd_additional_cnv_tasks.sh#L46)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

missing space
</blockquote></details>

Done.
___
*[`src/eggd_additional_cnv_tasks.sh` line 51 at r2](https://reviewable.io/reviews/eastgenomics/eggd_additional_cnv_tasks/1#-N9gJ97F2BAJd0ANSZhC:-N9pgoY30RWnMYhpocoa:bt7ev1l) ([raw file](https://github.com/eastgenomics/eggd_additional_cnv_tasks/blob/ba97b9dd7bffada256a10408c46398694a52037d/src/eggd_additional_cnv_tasks.sh#L51)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

do you need all the blank lines in the if/elif/else ?
</blockquote></details>

it feels too cramped otherwise but can change it.

**Review by Addy81 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_additional_cnv_tasks/1)* status: 9 of 13 files reviewed, 13 unresolved discussions (waiting on @Addy81, @Aisha-D, @jethror1, and @mattgarner)

___
*[`resources/home/dnanexus/make_seg.py` line 50 at r2](https://reviewable.io/reviews/eastgenomics/eggd_additional_cnv_tasks/1#-N9gI7Z96Givea6YKDf6:-N9qV041BObCd-lGOIqI:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_additional_cnv_tasks/blob/ba97b9dd7bffada256a10408c46398694a52037d/resources/home/dnanexus/make_seg.py#L50)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

this is a more reliable way to strip the path and any number of suffixes:
```
>>> from pathlib import Path
>>> file='some/path/to/file_with_suffixes.vcf.gz'
>>> Path(file).name.replace(''.join(Path(file).suffixes), '')
'file_with_suffixes'
```

then you can combine with below as:
```
output_seg = f'{Path(patient).name.replace(''.join(Path(patient).suffixes), '.seg')}'
```
</blockquote></details>

Done.

**Review by Addy81 — COMMENTED** [review]
:lgtm:

Run as default: https://platform.dnanexus.com/projects/GFPFjZQ4GVVKypPy26q2KxB5/monitor/job/GFzkj6j4GVV2q4gF4fxzv6Jb
Run with length off: https://platform.dnanexus.com/projects/GFPFjZQ4GVVKypPy26q2KxB5/monitor/job/GFzkjQj4GVV7V6qk4x5qQKkk
Run with seg off:  https://platform.dnanexus.com/projects/GFPFjZQ4GVVKypPy26q2KxB5/monitor/job/GFzkjY04GVV0QVV9KfQyp0bZ
Both turned off: https://platform.dnanexus.com/projects/GFPFjZQ4GVVKypPy26q2KxB5/monitor/job/GFzkjfj4GVV17JQ62V5Qp72F - fails as expected
Run with empty vcf: https://platform.dnanexus.com/projects/GFPFjZQ4GVVKypPy26q2KxB5/monitor/job/GFzkp304GVVKKzF1J2X44V7v

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_additional_cnv_tasks/1#-:-N9qVeuI8mhVmp2e6NcI:b-tsctx3)* status: 9 of 13 files reviewed, 13 unresolved discussions (waiting on @Addy81, @Aisha-D, @jethror1, and @mattgarner)

**Review by Addy81 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_additional_cnv_tasks/1)* status: 9 of 13 files reviewed, 13 unresolved discussions (waiting on @Aisha-D, @jethror1, and @mattgarner)

___
*[`dxapp.json` line 23 at r2](https://reviewable.io/reviews/eastgenomics/eggd_additional_cnv_tasks/1#-N9kV0Nf3uT9P8ec0mQv:-N9qWokTC3lkWRAOz_-5:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_additional_cnv_tasks/blob/ba97b9dd7bffada256a10408c46398694a52037d/dxapp.json#L23)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

I don't think these should be x_only

It could work when there are only 2 things the app does, but if we add a third and only want 2 of the three it doesn't work

Can they just be bools which switch that thing on and off? This would let you ask for A and C from a possible set of outputs A/B/C
</blockquote></details>

Done

**Review by jethror1 — APPROVED** [review]
> Reviewed 3 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_additional_cnv_tasks/1)* status: 12 of 13 files reviewed, 5 unresolved discussions (waiting on @Aisha-D, @jethror1, and @mattgarner)

**Comment by jethror1** [comment]
Happy with PR, @mattgarner and @Aisha-D to close comments

**Review by Aisha-D — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_additional_cnv_tasks/1#-:-N9qZvw4-tq87m8VT5Ul:bnfp4nl)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @Aisha-D, @jethror1, and @mattgarner)

**Review by mattgarner — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_additional_cnv_tasks/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Addy81)

**Pull request merged**
